name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        symfony: ['^6.4', '^7.0']
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: xdebug
      - run: composer update symfony/http-foundation:${{ matrix.symfony }} symfony/http-kernel:${{ matrix.symfony }} symfony/uid:${{ matrix.symfony }} --no-interaction
      - run: vendor/bin/php-cs-fixer fix --diff --dry-run
      - run: vendor/bin/phpstan analyse --no-progress
      - run: vendor/bin/phpunit --coverage-text
